apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-app-deployment
spec:
  selector:
    matchLabels: 
      app: hpa-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hpa-app
    spec:
      containers:
        - name: hpa-app
          image: shestera/scaletestapp
          ports:
            - containerPort: 8080
          resources:
            requests: 
              cpu: "1"
              memory: "40Mi"
            limits: 
              cpu: "1"
              memory: "40Mi"